version: '3'

tasks:
  m1-switch:
    desc: "Run nix-darwin rebuild switch for macOS"
    cmds:
      - sudo nix run nix-darwin/master#darwin-rebuild -- switch --flake .#darwin-macbook-m1

  homelab-switch:
    desc: "Run nixos-rebuild switch for Linux"
    cmds:
      - nixos-rebuild switch --flake .#linux-homelab-x86

  nvim-reload:
    desc: "Reload nvim configuration by reinstalling the nix profile"
    cmds:
      - nix profile remove dotfiles/nvim
      - nix profile install .?dir=dotfiles/nvim#nvim

  default:
    desc: "Show available tasks"
    cmds:
      - task --list-all

