# Start AeroSpace at login
start-at-login = true

# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# 'after-startup-command' is run after 'after-login-command'
## Run Sketchybar together with AeroSpace
# sketchbar has a built-in detection of already running process,
# so it won't be run twice on AeroSpace restart
after-startup-command = [
	'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0',
]

# Notify Sketchybar about workspace change
exec-on-workspace-change = [
]


# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 60

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 16
inner.vertical = 16
outer.left = 16
outer.bottom = 16
outer.top = 16
outer.right = 16

# See https://nikitabobko.github.io/AeroSpace/guide#exec-env-vars
[exec] # Again, you don't need to copy all config sections to your config.
inherit-env-vars = true # If you don't touch "exec" section,
[exec.env-vars] # it will fallback to "default-config.toml"
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
[mode.main.binding]

# Disable the shortcut hide application
cmd-h = []

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# You can uncomment this line to open up terminal with alt + enter shortcut
# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-ctrl-shift-v = 'layout tiles horizontal vertical'
alt-ctrl-shift-d = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -200'
alt-shift-equal = 'resize smart +200'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspce
ctrl-shift-alt-h = 'workspace 1'
ctrl-shift-alt-comma = 'workspace 2'
ctrl-shift-alt-period = 'workspace 3'
ctrl-shift-alt-n = 'workspace 4'
ctrl-shift-alt-e = 'workspace 5'
ctrl-shift-alt-i = 'workspace 6'
ctrl-shift-alt-l = 'workspace 7'
ctrl-shift-alt-u = 'workspace 8'
ctrl-shift-alt-y = 'workspace 9'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
ctrl-shift-alt-keypad1 = 'move-node-to-workspace 1'
ctrl-shift-alt-keypad2 = 'move-node-to-workspace 2'
ctrl-shift-alt-keypad3 = 'move-node-to-workspace 3'
ctrl-shift-alt-keypad4 = 'move-node-to-workspace 4'
ctrl-shift-alt-keypad5 = 'move-node-to-workspace 5'
ctrl-shift-alt-keypad6 = 'move-node-to-workspace 6'
ctrl-shift-alt-keypad7 = 'move-node-to-workspace 7'
ctrl-shift-alt-keypad8 = 'move-node-to-workspace 8'
ctrl-shift-alt-keypad9 = 'move-node-to-workspace 9'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
shift-ctrl-alt-g = 'workspace-back-and-forth'
shift-ctrl-alt-f = 'fullscreen'
shift-ctrl-alt-q = 'enable toggle'
shift-ctrl-alt-b = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'


# Development Tools (Workspace 1)
[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = [
    'layout tiling',
    'move-node-to-workspace 1'
]

# Browsers (Workspace 2)
[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = [
    'layout tiling',
    'move-node-to-workspace 2'
]

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = [
    'layout tiling',
    'move-node-to-workspace 2'
]

[[on-window-detected]]
if.app-id = 'com.google.Chrome.dev'
run = [
    'layout tiling',
    'move-node-to-workspace 2'
]

#  Tools (Workspace 2)
# [[on-window-detected]]
# run = ['move-node-to-workspace 2']


# Design Tools (Workspace 4)
# [[on-window-detected]]
# if.app-id = 'com.figma.Desktop'
# run = [
#     'layout tiling',
#     'move-node-to-workspace 4'
# ]

# Notes & Documentation (Workspace 5)
# [[on-window-detected]]
# if.app-id = 'md.obsidian'
# run = [
#     'layout tiling',
#     'move-node-to-workspace 5'
# ]
#
# [[on-window-detected]]
# if.app-id = 'com.apple.Notes'
# run = [
#     'layout tiling',
#     'move-node-to-workspace 5'
# ]
#
# [[on-window-detected]]
# if.app-id = 'com.apple.TextEdit'
# run = [
#     'layout tiling',
#     'move-node-to-workspace 5'
# ]

# Project Management (Workspace 5)
[[on-window-detected]]
if.app-id = 'com.linear'
run = [
    'layout tiling',
    'move-node-to-workspace 5'
]

# [[on-window-detected]]
# if.app-id = 'com.apple.mail'
# run = [
#     'layout tiling',
#     'move-node-to-workspace 6'
# ]

# Communication & Social App (Workspace 7)
    
# [[on-window-detected]]
# if.app-id = 'com.hnc.Discord'
# run = ['layout tiling', 'move-node-to-workspace 7']
#
#
# [[on-window-detected]]
# if.app-id = 'com.apple.MobileSMS'
# run = ['layout tiling', 'move-node-to-workspace 7']
#
#
# [[on-window-detected]]
# if.app-id = 'net.whatsapp.WhatsApp'
# run = ['layout tiling', 'move-node-to-workspace 7']
#
#
# [[on-window-detected]]
# if.app-id = 'com.microsoft.teams2'
# run = ['layout tiling', 'move-node-to-workspace 7']
#

# System Windows (Floating)
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'design.yugen.Flow'
run = ['layout floating']

# Catchall - Send unmatched windows to workspace 9
[[on-window-detected]]
run = [
    'layout tiling',
    'move-node-to-workspace 9'
]
