require("mini.ai").setup({})
require("mini.surround").setup({})
require("mini.comment").setup({})
require("mini.pairs").setup({})
require("mini.bufremove").setup({})
require("mini.bracketed").setup({})
