#!/bin/bash
# Display the list of test files in a fuzzy finder and execute a selected one

cd $DYLAN_PATH

# Check if the --watch argument is provided
WATCH_FLAG=""
if [[ "$1" == "--watch" ]]; then
  WATCH_FLAG="--watch"
  fi

FILEPATH="app/src/$(git ls-files "*.test.tsx" | sed 's:^app/src/::' | fzf --header "Select a test to run")"
FILEPATH_FROM_ROOT_DIR=$(echo "$FILEPATH" | sed 's:.*/src/:src/:' | sed 's:\.test\.tsx:\.tsx:')

pnpm jest --runTestsByPath $FILEPATH --coverage=true --coverageReporters="text" --collectCoverageFrom="$FILEPATH_FROM_ROOT_DIR"
#pnpm jest --runTestsByPath $FILEPATH --coverage=true --coverageReporters="text" --collectCoverageFrom="$FILEPATH_FROM_ROOT_DIR" 
