#!/bin/bash

CYPRESS_CONFIG="cypress.config.ts"
branch=$(git branch --show-current)
branch_slug=${branch//\//-}
LOCAL_API_URL="https://localhost:9443/api"
LOCAL_SERVER_URL="https://localhost:9443"
REMOTE_API_URL="https://${branch_slug}-api.test.shorthand.com"
REMOTE_SERVER_URL="https://${branch_slug}.test.shorthand.com/"

cd test

# If local copy exists, toggle 'off'
if [ -f "${CYPRESS_CONFIG}.local" ]; then
  # Restoring the file
  mv "${CYPRESS_CONFIG}.local" "${CYPRESS_CONFIG}"
  echo "Cypress now points to the local server"
else
  # Create a local copy
  cp "${CYPRESS_CONFIG}" "${CYPRESS_CONFIG}.local"
  
  # Replace the content (on macOS, -i requires a backup extension)
  sed -i '' "s|${LOCAL_API_URL}|${REMOTE_API_URL}|g" "${CYPRESS_CONFIG}"
  sed -i '' "s|${LOCAL_SERVER_URL}|${REMOTE_SERVER_URL}|g" "${CYPRESS_CONFIG}"

  echo "Cypress now points to the remote server"
fi
